export let taskList = [
    {
        taskName: "test",
        leader: 'wjz',
        disease: "糖尿病",
        modelname:"dqn",
        dataset:"diabetes",
        createtime:"2024/3/22",
    },
    {
        taskName: "test",
        leader: 'ym',
        disease: "糖尿病",
        modelname:"knn",
        dataset:"diabetes",
        createtime:"2024/3/22",
    },

    {
        taskName: "test",
        leader: 'ym',
        disease: "糖尿病",
        modelname:"dqn",
        dataset:"diabetes",
        createtime:"2024/3/22",
    },{
        taskName: "test",
        leader: 'ym',
        disease: "糖尿病",
        modelname:"dqn",
        dataset:"diabetes",
        createtime:"2024/3/22",
    },
    {
        taskName: "test",
        leader: 'wjz',
        disease: "糖尿病",
        modelname:"dqn",
        dataset:"diabetes",
        createtime:"2024/3/22",
    }, 
    {
        taskName: "test",
        leader: 'ym',
        disease: "糖尿病",
        modelname:"DDPG",
        dataset:"diabetes",
        createtime:"2024/3/22",
    },
    {
        taskName: "test",
        leader: 'ym',
        disease: "糖尿病",
        modelname:"PPO",
        dataset:"diabetes",
        createtime:"2024/3/22",
    },
    {
        taskName: "test",
        leader: 'ym',
        disease: "糖尿病",
        modelname:"PPO",
        dataset:"diabetes",
        createtime:"2024/3/22",
    },
    {
        taskName: "test",
        leader: 'ym',
        disease: "糖尿病",
        modelname:"dqn",
        dataset:"diabetes",
        createtime:"2024/3/22",
    },
    {
        taskName: "test",
        leader: 'ym',
        disease: "糖尿病",
        modelname:"dqn",
        dataset:"diabetes",
        createtime:"2024/3/22",
    },
    {
        taskName: "test",
        leader: 'ym',
        disease: "糖尿病",
        modelname:"dqn",
        dataset:"diabetes",
        createtime:"2024/3/22",
    },
    {
        taskName: "test",
        leader: 'ym',
        disease: "糖尿病",
        modelname:"dqn",
        dataset:"diabetes",
        createtime:"2024/3/22",
    },
    {
        taskName: "test",
        leader: 'ym',
        disease: "糖尿病",
        modelname:"dqn",
        dataset:"diabetes",
        createtime:"2024/3/22",
    },
    {
        taskName: "test",
        leader: 'ym1111111111111',
        disease: "糖尿病",
        modelname:"dqn",
        dataset:"diabetes",
        createtime:"2024/3/22",
    },

    {
        taskName: "test",
        leader: 'ym111111111111111',
        disease: "糖尿病",
        modelname:"dqn",
        dataset:"diabetes",
        createtime:"2024/3/22",
    },
    {
        taskName: "test",
        leader: 'ym111111111111111',
        disease: "糖尿病",
        modelname:"dqn",
        dataset:"diabetes",
        createtime:"2024/3/22",
    },
    {
        taskName: "test",
        leader: 'ym',
        disease: "糖尿病",
        modelname:"dqn",
        dataset:"diabetes",
        createtime:"2024/3/22",
    },
    {
        taskName: "test",
        leader: 'ym',
        disease: "糖尿病",
        modelname:"dqn",
        dataset:"diabetes",
        createtime:"2024/3/22",
    },
    {
        taskName: "test",
        leader: 'ym',
        disease: "糖尿病",
        modelname:"dqn",
        dataset:"diabetes",
        createtime:"2024/3/22",
    },{
        taskName: "test",
        leader: 'ym',
        disease: "糖尿病",
        modelname:"dqn",
        dataset:"diabetes",
        createtime:"2024/3/22",
    },{
        taskName: "test",
        leader: 'ym',
        disease: "糖尿病",
        modelname:"dqn",
        dataset:"diabetes",
        createtime:"2024/3/22",
    },
    {
        taskName: "test111111111",
        leader: 'ymqqqqqqq',
        disease: "糖尿病",
        modelname:"dqn",
        dataset:"diabetes",
        createtime:"2024/3/22",
    },
    {
        taskName: "test",
        leader: 'ym',
        disease: "糖尿病",
        modelname:"dqn",
        dataset:"diabetes",
        createtime:"2024/3/22",
    },{
        taskName: "test",
        leader: 'ym',
        disease: "糖尿病",
        modelname:"dqn",
        dataset:"diabetes",
        createtime:"2024/3/22",
    },{
        taskName: "test",
        leader: 'ym',
        disease: "糖尿病",
        modelname:"dqn",
        dataset:"diabetes10",
        createtime:"2024/3/22",
    },{
        taskName: "test",
        leader: 'ym',
        disease: "糖尿病",
        modelname:"dqn",
        dataset:"diabetes",
        createtime:"2024/3/22",
    },

  ];
  
